spring.application.name=ecsite

# データベース接続設定（ファイル永続モード）
spring.datasource.url=jdbc:h2:file:./data/ecsitedb;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver

# ユーザー名とパスワード設定
spring.datasource.username=root
spring.datasource.password=root

# H2コンソール設定
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# データベース初期化設定
spring.sql.init.mode=always
# テーブル定義ファイル                 
spring.sql.init.schema-locations=classpath:schema.sql 
# 初期データ挿入ファイル
spring.sql.init.data-locations=classpath:data.sql

# 自動コミットを無効化（トランザクション管理用）
spring.datasource.hikari.auto-commit=false


logging.level.org.springframework.security=DEBUG


